import {parseLrc,activeLine} from './lyrics.mjs';
import {SPOTIFY_CLIENT_ID} from './config.js';
const $=id=>document.getElementById(id), redirect=location.origin+location.pathname.replace(/index\.html$/,'');
const keys={client:'lyricsync.client',token:'lyricsync.token',auth:'lyricsync.auth'};
let token=JSON.parse(sessionStorage.getItem(keys.token)||'null'), track=null, lines=[], base=0, sampled=0, playing=false, demo=false, selected=-2, generation=0, timer, busy=false, cooldown=0;
const status=text=>$('status').textContent=text;
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join('');
const fmt=ms=>`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;
$('redirect').textContent=redirect;
$('clientId').value=SPOTIFY_CLIENT_ID||localStorage.getItem(keys.client)||'';
async function exchange(params){const res=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)});if(!res.ok)throw Error('Spotify login expired or could not be completed. Please connect again.');const data=await res.json();token={...data,refresh_token:data.refresh_token||token?.refresh_token,expires:Date.now()+data.expires_in*1000};sessionStorage.setItem(keys.token,JSON.stringify(token));}
$('connectForm').addEventListener('submit',async e=>{e.preventDefault();try{const client=$('clientId').value.trim();if(!/^[a-f\d]{32}$/i.test(client)){$('appSettings').open=true;$('clientId').focus();throw Error('Spotify sign-in needs the site owner to configure a Spotify app Client ID. You can explore the demo in the meantime.');}localStorage.setItem(keys.client,client);const verifier=random(),state=random();sessionStorage.setItem(keys.auth,JSON.stringify({verifier,state}));const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));const challenge=btoa(String.fromCharCode(...new Uint8Array(digest))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');location.assign('https://accounts.spotify.com/authorize?'+new URLSearchParams({client_id:client,response_type:'code',redirect_uri:redirect,scope:'user-read-currently-playing',code_challenge_method:'S256',code_challenge:challenge,state}));}catch(err){status(err.message);}});
async function spotify(){if(!token)throw Error('Connect Spotify to see your current song.');if(Date.now()>token.expires-30000)await exchange({grant_type:'refresh_token',refresh_token:token.refresh_token,client_id:localStorage.getItem(keys.client)});const res=await fetch('https://api.spotify.com/v1/me/player/currently-playing',{headers:{Authorization:`Bearer ${token.access_token}`}});if(res.status===204)return null;if(res.status===429){cooldown=Date.now()+Math.max(5,Number(res.headers.get('Retry-After'))||30)*1000;throw Error('Spotify is busy. Waiting before checking again.');}if(res.status===401){token=null;sessionStorage.removeItem(keys.token);$('setup').hidden=false;throw Error('Your Spotify session expired. Connect again.');}if(res.status===403)throw Error('Spotify denied access. Check that this account is allowed in your developer app.');if(!res.ok)throw Error('Spotify is temporarily unavailable. We will try again.');return res.json();}
function empty(title,body){$('lyrics').replaceChildren();const box=document.createElement('div');box.className='empty';const h=document.createElement('h2'),p=document.createElement('p');h.textContent=title;p.textContent=body;box.append(h,p);$('lyrics').append(box);}
function renderLyrics(){selected=-2;$('lyrics').replaceChildren(...lines.map(line=>{const p=document.createElement('p');p.className='line';p.textContent=line.text;return p;}));}
function setTrack(item){track=item;$('title').textContent=item.name;$('artist').textContent=item.artists.map(a=>a.name).join(', ');const art=item.album?.images?.[0]?.url;$('art').hidden=!art;$('artPlaceholder').hidden=!!art;if(art)$('art').src=art;else $('art').removeAttribute('src');const url=item.external_urls?.spotify;$('trackLink').hidden=!url;if(url)$('trackLink').href=url;$('duration').textContent=fmt(item.duration_ms);}
async function getLyrics(item,version){lines=[];empty('Finding the words…','Looking for lyrics for this recording.');try{const params=new URLSearchParams({track_name:item.name,artist_name:item.artists[0]?.name||'',album_name:item.album?.name||'',duration:Math.round(item.duration_ms/1000)});const res=await fetch('https://lrclib.net/api/get?'+params,{signal:AbortSignal.timeout(15000)});if(version!==generation)return;if(res.status===404){empty('No lyrics for this recording yet.','Try another song. Some tracks do not have lyrics on LRCLIB.');return;}if(!res.ok)throw Error('Lyrics are temporarily unavailable. Press Refresh to retry.');const data=await res.json();if(version!==generation)return;if(data.instrumental){empty('Let the music speak.','This track is marked as instrumental.');return;}lines=parseLrc(data.syncedLyrics||'');if(lines.length){$('lyricSource').textContent='SYNCED · LRCLIB';renderLyrics();}else if(data.plainLyrics){$('lyricSource').textContent='UNSYNCED · LRCLIB';$('lyrics').replaceChildren(...data.plainLyrics.split('\n').map(text=>{const p=document.createElement('p');p.className='line';p.textContent=text||' ';return p;}));}else empty('No lyrics available.','LRCLIB has no lyrics for this recording.');}catch(err){if(version===generation)empty('Could not load lyrics.',err.message);}}
async function poll(force=false){clearTimeout(timer);if(busy||demo||!token)return;if(Date.now()<cooldown){timer=setTimeout(()=>poll(),cooldown-Date.now());return;}busy=true;const version=generation;try{const data=await spotify();if(version!==generation||demo)return;if(!data?.item||data.item.type!=='track'){playing=false;track=null;lines=[];generation++;$('mode').textContent='WAITING FOR SPOTIFY';$('title').textContent='Nothing playing';$('artist').textContent='Start a song in Spotify';$('trackLink').hidden=true;$('art').hidden=true;$('artPlaceholder').hidden=false;empty('Waiting for your music.','Start a song in Spotify on any active device.');status('No active song. Open Spotify and press play.');return;}base=data.progress_ms||0;sampled=performance.now();playing=data.is_playing;$('mode').textContent=playing?'NOW PLAYING':'PAUSED';status(playing?'Connected · Following your Spotify playback':'Connected · Playback paused');if(track?.id!==data.item.id||force){setTrack(data.item);getLyrics(data.item,++generation);}}catch(err){playing=false;status(err.message);}finally{busy=false;if(token&&!demo)timer=setTimeout(()=>poll(),Math.max(5000,cooldown-Date.now()));}}
function reset(){generation++;clearTimeout(timer);token=null;sessionStorage.removeItem(keys.token);demo=false;playing=false;track=null;lines=[];base=0;setTrack({name:'Your next favorite moment',artists:[{name:'Start a song in Spotify'}],duration_ms:0});track=null;$('setup').hidden=false;$('mode').textContent='NOW PLAYING';$('lyricSource').textContent='LRCLIB';empty('Every song has a story.','Connect Spotify to follow along.');status('Disconnected.');}
$('disconnect').onclick=reset;
$('settings').onclick=()=>{$('setup').hidden=!$('setup').hidden;if(!$('setup').hidden)$('signIn').focus();};
$('refresh').onclick=()=>{if(demo){sampled=performance.now();base=0;}else if(token)poll(true);else status('Connect Spotify first, or explore the demo.');};
$('offset').oninput=()=>{$('offsetValue').textContent=Number($('offset').value).toFixed(1)+'s';};
$('demo').onclick=()=>{generation++;clearTimeout(timer);demo=true;playing=true;base=0;sampled=performance.now();$('setup').hidden=true;$('mode').textContent='DEMO · NO AUDIO';$('lyricSource').textContent='ORIGINAL DEMO LYRICS';setTrack({id:'demo',name:'Between the Notes',artists:[{name:'LyricSync · visual preview'}],duration_ms:32000});lines=parseLrc('[00:00.00]Let the room fall quiet\n[00:04.00]Watch the colors come alive\n[00:08.00]Every word a little brighter\n[00:12.00]Every moment passing by\n[00:16.00]Somewhere in the spaces\n[00:20.00]Between the notes we know\n[00:24.00]We find a little feeling\n[00:28.00]And let the music flow');renderLyrics();status('Demo preview · Original sample words, no audio. Open Settings to connect Spotify.');};
setInterval(()=>{let pos=track?Math.min(track.duration_ms,base+(playing?performance.now()-sampled:0)):0;if(demo&&pos>=32000){sampled=performance.now();pos=0;}$('position').textContent=fmt(pos);$('bar').style.width=(track?.duration_ms?pos/track.duration_ms*100:0)+'%';if(!lines.length)return;const next=activeLine(lines,pos+Number($('offset').value)*1000);if(next!==selected){selected=next;[...$('lyrics').children].forEach((el,i)=>{el.classList.toggle('active',i===next);el.classList.toggle('past',i<next);if(i===next)el.setAttribute('aria-current','true');else el.removeAttribute('aria-current');});const el=$('lyrics').children[next];if(el&&$('follow').checked)$('lyrics').scrollTo({top:el.offsetTop-$('lyrics').offsetTop-$('lyrics').clientHeight/2+el.clientHeight/2,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}},250);
async function init(){const params=new URLSearchParams(location.search);if(params.has('code')||params.has('error')){history.replaceState({},'',redirect);try{const auth=JSON.parse(sessionStorage.getItem(keys.auth)||'null');sessionStorage.removeItem(keys.auth);if(params.has('error'))throw Error('Spotify connection was cancelled. You can try again.');if(!auth||params.get('state')!==auth.state)throw Error('Login verification failed. Please connect again.');await exchange({grant_type:'authorization_code',code:params.get('code'),redirect_uri:redirect,client_id:localStorage.getItem(keys.client),code_verifier:auth.verifier});}catch(err){status(err.message);return;}}if(token){$('setup').hidden=true;poll();}}
init();
